services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
    environment:
      - compose=true
    depends_on:
      - mariadb  # Säkerställer att PHP väntar på MariaDB innan den startar
  
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_USER: root  # Ändra användarnamnet till root om du vill använda root
      MYSQL_PASSWORD: mariadb  # Använd samma lösenord som i PHP-koden
      MYSQL_DATABASE: todo_list  # Ändra till "todo_list" istället för "moviestodo"
      MARIADB_ROOT_PASSWORD: mariadb  # Root-lösenordet för MariaDB
    ports:
      - 3306:3306  # MariaDB-porten
    volumes:
      - mariadb_data:/var/lib/mysql  # Persistent datalagring för MariaDB
      - ./src/seed:/docker-entrypoint-initdb.d/  # Om du har SQL-skript för att skapa databasen eller fylla den med data
  
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - 8080:8080  # Adminer för att hantera databasen via en webbläsare

volumes:
  mariadb_data:
