version: '3.8'
services:
  php:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - sqlite_data:/var/www/html/movies.sqlite  # Persist SQLite DB

volumes:
  sqlite_data: